### ISSUE TITLE
NPE FC in TwitterFragment

### ISSUE THREAD

**Issue by ligi** [criticalmaps/criticalmaps-android#92]
```
E/AndroidRuntime(27284): Process: de.stephanlindauer.criticalmaps, PID: 27284
E/AndroidRuntime(27284): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v4.widget.SwipeRefreshLayout.setRefreshing(boolean)' on a null object reference
E/AndroidRuntime(27284): 	at de.stephanlindauer.criticalmaps.fragments.TwitterFragment.displayNewData(TwitterFragment.java:91)
E/AndroidRuntime(27284): 	at de.stephanlindauer.criticalmaps.handler.TwitterGetHandler.onPostExecute(TwitterGetHandler.java:53)
E/AndroidRuntime(27284): 	at de.stephanlindauer.criticalmaps.handler.TwitterGetHandler.onPostExecute(TwitterGetHandler.java:16)
E/AndroidRuntime(27284): 	at android.os.AsyncTask.finish(AsyncTask.java:636)
E/AndroidRuntime(27284): 	at android.os.AsyncTask.access$500(AsyncTask.java:177)
E/AndroidRuntime(27284): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
E/AndroidRuntime(27284): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(27284): 	at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime(27284): 	at android.app.ActivityThread.main(ActivityThread.java:6872)
E/AndroidRuntime(27284): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27284): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(27284): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
E/AndroidRuntime(27284): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by cbalster** [comment]
probably the asynctask trying to do work on a view that's already been destroyed when it finishes. I guess this happens when you navigate more than one tab away from the twitter fragment?

**Comment by ligi** [comment]
I can reproduce it now kind of regularly by jumping between tabs wildly
Did not yet found a step by step way to reproduce

On 16.10.2015 00:47, Christian Balster wrote:
> probably the asynctask trying to do work on a view that's already been
> destroyed when it finishes. I guess this happens when you navigate more
> than one tab away from the twitter fragment?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/criticalmaps/criticalmaps-android/issues/92#issuecomment-148544668>.
> 


-- 
best regards,
ligi
http://ligi.de

**Comment by cbalster** [comment]
yeah, pretty sure that's it. try refreshing the twitterfeed and jump to the about tab as quickly as possible.
